var FontStyles;
(function (FontStyles) {
    FontStyles[FontStyles["Extalight"] = 0] = "Extalight";
    FontStyles[FontStyles["ExtaLight"] = 0] = "ExtaLight";
    FontStyles[FontStyles["Thin"] = 1] = "Thin";
    FontStyles[FontStyles["Light"] = 2] = "Light";
    FontStyles[FontStyles["Semilight"] = 3] = "Semilight";
    FontStyles[FontStyles["SemiLight"] = 3] = "SemiLight";
    FontStyles[FontStyles["Regular"] = 4] = "Regular";
    FontStyles[FontStyles["Plain"] = 5] = "Plain";
    FontStyles[FontStyles["Medium"] = 6] = "Medium";
    FontStyles[FontStyles["Semibold"] = 7] = "Semibold";
    FontStyles[FontStyles["SemiBold"] = 7] = "SemiBold";
    FontStyles[FontStyles["Bold"] = 8] = "Bold";
    FontStyles[FontStyles["Extabold"] = 9] = "Extabold";
    FontStyles[FontStyles["ExtaBold"] = 9] = "ExtaBold";
    FontStyles[FontStyles["Black"] = 10] = "Black";
    FontStyles[FontStyles["Thin Italic"] = 11] = "Thin Italic";
    FontStyles[FontStyles["Light Italic"] = 12] = "Light Italic";
    FontStyles[FontStyles["Italic"] = 13] = "Italic";
    FontStyles[FontStyles["Medium Italic"] = 14] = "Medium Italic";
    FontStyles[FontStyles["Bold Italic"] = 15] = "Bold Italic";
    FontStyles[FontStyles["ExtaBold Italic"] = 16] = "ExtaBold Italic";
    FontStyles[FontStyles["Black Italic"] = 17] = "Black Italic";
})(FontStyles || (FontStyles = {}));
export default FontStyles;
