var FontStyles;
(function (FontStyles) {
    FontStyles[FontStyles["extralight"] = 0] = "extralight";
    FontStyles[FontStyles["thin"] = 1] = "thin";
    FontStyles[FontStyles["ultralight"] = 2] = "ultralight";
    FontStyles[FontStyles["light"] = 3] = "light";
    FontStyles[FontStyles["book"] = 4] = "book";
    FontStyles[FontStyles["roman"] = 5] = "roman";
    FontStyles[FontStyles["semilight"] = 6] = "semilight";
    FontStyles[FontStyles["regular"] = 7] = "regular";
    FontStyles[FontStyles["plain"] = 10] = "plain";
    FontStyles[FontStyles["medium"] = 11] = "medium";
    FontStyles[FontStyles["semibold"] = 12] = "semibold";
    FontStyles[FontStyles["demi"] = 13] = "demi";
    FontStyles[FontStyles["demibold"] = 13] = "demibold";
    FontStyles[FontStyles["bold"] = 14] = "bold";
    FontStyles[FontStyles["extrabold"] = 15] = "extrabold";
    FontStyles[FontStyles["heavy"] = 16] = "heavy";
    FontStyles[FontStyles["black"] = 17] = "black";
    FontStyles[FontStyles["extra"] = 18] = "extra";
    FontStyles[FontStyles["semi"] = 19] = "semi";
})(FontStyles || (FontStyles = {}));
export default FontStyles;
