enum NodeTypes {
  DOCUMENT = 'DOCUMENT',
  PAGE = 'PAGE',
  FRAME = 'FRAME',
  GROUP = 'GROUP',
  SLICE = 'SLICE',
  RECTANGLE = 'RECTANGLE',
  LINE = 'LINE',
  ELLIPSE = 'ELLIPSE',
  POLYGON = 'POLYGON',
  STAR = 'STAR',
  VECTOR = 'VECTOR',
  TEXT = 'TEXT',
  COMPONENT = 'COMPONENT',
  INSTANCE = 'INSTANCE',
  BOOLEAN_OPERATION = 'BOOLEAN_OPERATION'
}

export default NodeTypes;