enum TokenTypes {
    CORNER_RADIUS = 'CORNER_RADIUS',
    EFFECT = 'EFFECT',
    FILL_COLOR = 'FILL_COLOR',
    OPACITY = 'OPACITY',
    STROKE_COLOR = 'STROKE_COLOR',
    STROKE_DASH = 'STROKE_DASH',
    STROKE_WIDTH_ALIGH = 'STROKE_WIDTH_ALIGH'
}

export default TokenTypes;
